// <auto-generated />
using System;
using CreditFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditFlow.Infrastructure.Migrations
{
    [DbContext(typeof(CreditFlowDbContext))]
    partial class CreditFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditFlow.Domain.Applicants.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Applicants", (string)null);
                });

            modelBuilder.Entity("CreditFlow.Domain.LoanApplications.LoanApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReasons")
                        .HasColumnType("text")
                        .HasColumnName("RejectionReasons");

                    b.Property<int>("RequestedTermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LoanApplications", (string)null);
                });

            modelBuilder.Entity("CreditFlow.Domain.Applicants.Applicant", b =>
                {
                    b.OwnsOne("CreditFlow.Domain.ValueObjects.EmploymentInfo", "EmploymentInfo", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EmployerName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("EmployerName");

                            b1.Property<int>("YearsEmployed")
                                .HasColumnType("integer")
                                .HasColumnName("YearsEmployed");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");

                            b1.OwnsOne("CreditFlow.Domain.ValueObjects.Money", "MonthlyIncome", b2 =>
                                {
                                    b2.Property<Guid>("EmploymentInfoApplicantId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("MonthlyIncomeAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("MonthlyIncomeCurrency");

                                    b2.HasKey("EmploymentInfoApplicantId");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("EmploymentInfoApplicantId");
                                });

                            b1.Navigation("MonthlyIncome")
                                .IsRequired();
                        });

                    b.OwnsOne("CreditFlow.Domain.ValueObjects.FinancialObligations", "FinancialObligations", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("LastCheckedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DebtLastCheckedAtUtc");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");

                            b1.OwnsOne("CreditFlow.Domain.ValueObjects.Money", "ExistingMonthlyDebt", b2 =>
                                {
                                    b2.Property<Guid>("FinancialObligationsApplicantId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ExistingMonthlyDebtAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("ExistingMonthlyDebtCurrency");

                                    b2.HasKey("FinancialObligationsApplicantId");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("FinancialObligationsApplicantId");
                                });

                            b1.Navigation("ExistingMonthlyDebt")
                                .IsRequired();
                        });

                    b.OwnsOne("CreditFlow.Domain.ValueObjects.PersonalInfo", "PersonalInfo", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date")
                                .HasColumnName("DateOfBirth");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("NationalId")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("NationalId");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.Navigation("EmploymentInfo")
                        .IsRequired();

                    b.Navigation("FinancialObligations")
                        .IsRequired();

                    b.Navigation("PersonalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("CreditFlow.Domain.LoanApplications.LoanApplication", b =>
                {
                    b.OwnsOne("CreditFlow.Domain.ValueObjects.Money", "RequestedAmount", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("RequestedAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("RequestedAmountCurrency");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.OwnsOne("CreditFlow.Domain.ValueObjects.CreditAssessment", "CreditAssessment", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AssessedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("AssessedAtUtc");

                            b1.Property<string>("Reasons")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AssessmentReasons");

                            b1.Property<string>("RiskTier")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("RiskTier");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");

                            b1.OwnsOne("CreditFlow.Domain.ValueObjects.Percentage", "DebtToIncomeRatio", b2 =>
                                {
                                    b2.Property<Guid>("CreditAssessmentLoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("decimal(5,2)")
                                        .HasColumnName("DebtToIncomeRatioPercentage");

                                    b2.HasKey("CreditAssessmentLoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("CreditAssessmentLoanApplicationId");
                                });

                            b1.OwnsOne("CreditFlow.Domain.ValueObjects.CreditScore", "CreditScore", b2 =>
                                {
                                    b2.Property<Guid>("CreditAssessmentLoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("CreditScore");

                                    b2.HasKey("CreditAssessmentLoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("CreditAssessmentLoanApplicationId");
                                });

                            b1.Navigation("CreditScore")
                                .IsRequired();

                            b1.Navigation("DebtToIncomeRatio")
                                .IsRequired();
                        });

                    b.OwnsOne("CreditFlow.Domain.ValueObjects.LoanTerms", "ApprovedTerms", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("TermMonths")
                                .HasColumnType("integer")
                                .HasColumnName("ApprovedTermMonths");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");

                            b1.OwnsOne("CreditFlow.Domain.ValueObjects.InterestRate", "InterestRate", b2 =>
                                {
                                    b2.Property<Guid>("LoanTermsLoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("LoanTermsLoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanTermsLoanApplicationId");

                                    b2.OwnsOne("CreditFlow.Domain.ValueObjects.Percentage", "AnnualRate", b3 =>
                                        {
                                            b3.Property<Guid>("InterestRateLoanTermsLoanApplicationId")
                                                .HasColumnType("uuid");

                                            b3.Property<decimal>("Value")
                                                .HasColumnType("decimal(5,2)")
                                                .HasColumnName("AnnualInterestRatePercentage");

                                            b3.HasKey("InterestRateLoanTermsLoanApplicationId");

                                            b3.ToTable("LoanApplications");

                                            b3.WithOwner()
                                                .HasForeignKey("InterestRateLoanTermsLoanApplicationId");
                                        });

                                    b2.Navigation("AnnualRate")
                                        .IsRequired();
                                });

                            b1.OwnsOne("CreditFlow.Domain.ValueObjects.Money", "MonthlyPayment", b2 =>
                                {
                                    b2.Property<Guid>("LoanTermsLoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("MonthlyPaymentAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("MonthlyPaymentCurrency");

                                    b2.HasKey("LoanTermsLoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanTermsLoanApplicationId");
                                });

                            b1.OwnsOne("CreditFlow.Domain.ValueObjects.Money", "PrincipalAmount", b2 =>
                                {
                                    b2.Property<Guid>("LoanTermsLoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ApprovedPrincipalAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("ApprovedPrincipalCurrency");

                                    b2.HasKey("LoanTermsLoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanTermsLoanApplicationId");
                                });

                            b1.Navigation("InterestRate")
                                .IsRequired();

                            b1.Navigation("MonthlyPayment")
                                .IsRequired();

                            b1.Navigation("PrincipalAmount")
                                .IsRequired();
                        });

                    b.Navigation("ApprovedTerms");

                    b.Navigation("CreditAssessment");

                    b.Navigation("RequestedAmount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
