using CreditFlow.Domain.Applicants;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CreditFlow.Infrastructure.Persistence.Configurations
{
	public sealed class ApplicantConfiguration : IEntityTypeConfiguration<Applicant>
	{
		public void Configure(EntityTypeBuilder<Applicant> builder)
		{
			builder.ToTable("Applicants");

			builder.HasKey(a => a.Id);

			// Guid is generated by the domain (Applicant.Register calls
			// Guid.CreateVersion7() itself), so EF Core must NOT try to generate its
			// own value on insert.
			builder.Property(a => a.Id).ValueGeneratedNever();

			builder.Property(a => a.RegisteredAtUtc).IsRequired();

			// PersonalInfo is an owned type: its fields become columns
			// directly on the Applicants table (e.g. PersonalInfo_FirstName),
			// not a separate table with a foreign key.
			builder.OwnsOne(a => a.PersonalInfo, personalInfo =>
			{
				personalInfo.Property(p => p.FirstName).HasColumnName("FirstName").HasMaxLength(100).IsRequired();
				personalInfo.Property(p => p.LastName).HasColumnName("LastName").HasMaxLength(100).IsRequired();
				personalInfo.Property(p => p.DateOfBirth).HasColumnName("DateOfBirth").IsRequired();
				personalInfo.Property(p => p.NationalId).HasColumnName("NationalId").HasMaxLength(20).IsRequired();
			});

			builder.OwnsOne(a => a.EmploymentInfo, employmentInfo =>
			{
				employmentInfo.Property(e => e.EmployerName).HasColumnName("EmployerName").HasMaxLength(200).IsRequired();
				employmentInfo.Property(e => e.YearsEmployed).HasColumnName("YearsEmployed").IsRequired();

				// flattens everything onto the same Applicants table
				employmentInfo.OwnsOne(e => e.MonthlyIncome, money =>
				{
					money.Property(m => m.Amount).HasColumnName("MonthlyIncomeAmount").HasColumnType("decimal(18,2)").IsRequired();
					money.Property(m => m.Currency).HasColumnName("MonthlyIncomeCurrency").HasMaxLength(3).IsRequired();
				});
			});

			builder.OwnsOne(a => a.FinancialObligations, financialObligations =>
			{
				financialObligations.Property(f => f.LastCheckedAtUtc).HasColumnName("DebtLastCheckedAtUtc");
				financialObligations.OwnsOne(f => f.ExistingMonthlyDebt, money =>
				{
					money.Property(m => m.Amount).HasColumnName("ExistingMonthlyDebtAmount").HasColumnType("decimal(18,2)").IsRequired();
					money.Property(m => m.Currency).HasColumnName("ExistingMonthlyDebtCurrency").HasMaxLength(3).IsRequired();
				});
			});

		}
	}
}
